version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    container_name: emergency-ai-assistant
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

